name: sync

on:
  push:
    branches:
      - feature/*

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync
        env:
          SOURCE_BRANCH: ${{ inputs.source-branch }}
          DESTINATION_BRANCH: ${{ inputs.destination-branch }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git fetch origin $SOURCE_BRANCH
          git checkout $DESTINATION_BRANCH
          git merge --no-ff $SOURCE_BRANCH
          git push origin $DESTINATION_BRANCH
