# File: .github/workflows/sync.yml

on:
  push:
    branches:
    - feature/*

jobs:
  pull-request1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "int-dev"
        
  pull-request2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "int-cert"
